### ISSUE TITLE
Paragraph inline link hover state

### ISSUE THREAD

**Issue by stephenravenscraft** [loyolauniversitychicago/loyola-template-4.0#36]
**Device:** MacBrook Pro
**Browser:** Chrome
- The gray background on the hover state of inline links needs to be lighter. Try $gray-extra-light.

**Comment by brianseifs4** [comment]
Added to Smartsheet

**Comment by stephenravenscraft** [comment]
This is completed. @brianseifs4, I will mark it a complete in the SmartSheet.

**Comment by stephenravenscraft** [comment]
This is completed. @brianseifs4, I will mark it a complete in the SmartSheet.

**Comment by stephenravenscraft** [comment]
This issue is closed.
